# Generated by Django 5.1.7 on 2025-03-22 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('barcode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('container_type', models.CharField(choices=[('PALLET', 'Pallet'), ('BOX', 'Box'), ('CASE', 'Case')], max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warehouse_id', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('BIN', 'Bin'), ('STG_IN', 'Pallet Staging Inbound'), ('STG_OUT', 'Pallet Staging Outbound'), ('RECEIVING', 'Receiving'), ('SHIPPING', 'Shipping'), ('DROP_ZONE', 'Drop Zone'), ('CART', 'Cart'), ('PALLETIZE', 'Palletize Area'), ('PROBLEM_SOLVING', 'Problem Solving Area'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged'), ('PICKING', 'Picking'), ('PACKING', 'Packing'), ('RETURNS_AREA', 'returns area')], max_length=50)),
                ('capacity_weight', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('capacity_volume', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('BLOCKED', 'Blocked'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=50)),
                ('item_restrictions', models.TextField(blank=True, null=True)),
                ('accessibility_priority', models.IntegerField(default=0)),
                ('coordinates_x', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coordinates_y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coordinates_z', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('whseSKU', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('KG', 'Kilograms'), ('LBS', 'Pounds'), ('M', 'Meters'), ('CM', 'Centimeters'), ('MM', 'Millimeters'), ('IN', 'Inches'), ('FT', 'Feet'), ('YD', 'Yards'), ('GAL', 'Gallons'), ('LT', 'Liters')], max_length=5, null=True)),
                ('vendorSKU', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('barcode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.container')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location')),
                ('product', models.ForeignKey(db_column='whseSKU', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Addition'), ('REMOVE', 'Removal')], max_length=10)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.inventory')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_from', to='warehouse.location')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_to', to='warehouse.location')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location'),
        ),
        migrations.CreateModel(
            name='MovementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_reason', models.CharField(blank=True, choices=[('INBOUND_STAGING', 'Inbound Staging'), ('OUTBOUND_STAGING', 'Outbound Staging'), ('PALLETIZATION', 'Palletization'), ('PROBLEM_SOLVING', 'Problem Solving'), ('TRUCK_LOADING', 'Truck Loading'), ('TRUCK_UNLOADING', 'Truck Unloading'), ('RETURNS', 'Returns'), ('CROSS_DOCK_UNLOADING', 'CROSS_DOCK_UNLOADING'), ('CROSS_DOCK_STAGING', 'CROSS_DOCK_STAGING'), ('INVENTORY_MOVEMENT', 'INVENTORY_MOVEMENT'), ('PICKING', 'PICKING'), ('STOWING', 'STOWING')], max_length=50, null=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('from_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='warehouse.container')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='warehouse.location')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_history', to='warehouse.inventory')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='warehouse.container')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='warehouse.location')),
                ('whseSKU', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_movements', to='warehouse.product')),
            ],
        ),
    ]
